name = "GymSpaces"
uuid = "4896a6fa-884d-11e9-35a0-9763e69c01ff"
authors = ["Kartikey Gupta <kartikeygupta9097@gmail.com>"]
version = "0.2.0"

[deps]
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"

[compat]
DataStructures = "0.17.7, 0.18"
julia = "1.1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
